services:
  php-fpm:
    build:
      args:
        APP_ENV: "prod"
        APP_SECRET: df6e7c36d834e87adc56f70ced9b2c81
        TZ: "Europe/Berlin"
    environment:
      APP_ENV: "prod"

  nginx:
    build:
      args:
        APP_ENV: "prod"
    environment:
      APP_ENV: "prod"
